CREATE TABLE D_EXAMSELECT(
   SEQ NUMBER(10),
   EXA_CODE NUMBER(10) NOT NULL,
   CONTENT VARCHAR2(2000) NOT NULL,
   WRO_ONE VARCHAR2(2000) NOT NULL,
   WRO_TWO VARCHAR2(2000) NOT NULL,
   WRO_THREE VARCHAR2(2000) NOT NULL,
   COR_ANSWER VARCHAR2(2000) NOT NULL,
   FILENAME VARCHAR2(100),
   CONSTRAINT D_EXAMSELECT_PK PRIMARY KEY(SEQ)
);


CREATE TABLE D_EXAMDESCRIPTIVE(
   SEQ NUMBER(10),
   EXA_CODE NUMBER(10) NOT NULL,
   CONTENT VARCHAR2(2000) NOT NULL,
   STANDARD VARCHAR2(2000) NOT NULL,
   FILENAME VARCHAR2(100),
   CONSTRAINT D_EXAMDESCRIPTIVE_PK PRIMARY KEY(SEQ)
);

CREATE TABLE D_ANSWERSCORE(
   ANS_SEQ NUMBER(10),
   CUR_EXACODE VARCHAR2(10) NOT NULL,
   STU_ID VARCHAR2(10) NOT NULL,
   ANSWER VARCHAR2(2000),
   NEWFILENAME VARCHAR2(100),
   "CHECK" CHAR(1) NOT NULL,
   JUMSU NUMBER(3) NOT NULL,
   CONSTRAINT D_ANSWERSCORE_PK PRIMARY KEY(ANS_SEQ)
);
 
  
CREATE TABLE D_CUREXA(
   CUREXA_CODE VARCHAR2(10),
   CUR_CODE VARCHAR2(10) NOT NULL,
   EXA_CODE NUMBER(10) NOT NULL,
   ALLOT NUMBER(3) NOT NULL,
   CONSTRAINT D_CUREXA_PK PRIMARY KEY(CUREXA_CODE)
);

CREATE TABLE D_EXAM(
   EXA_CODE NUMBER(10),
   EXA_MEAN CHAR(1) NOT NULL,
   CONSTRAINT D_EXAM_PK PRIMARY KEY(EXA_CODE)
);

CREATE TABLE D_CURRICULUM(
   CUR_CODE NUMBER(10),
   COU_CODE VARCHAR2(10) NOT NULL,
   SUB_CODE VARCHAR2(10) NOT NULL,
   CONSTRAINT D_CURRICULUM_PK PRIMARY KEY(CUR_CODE)
);

CREATE TABLE D_SUBJECT(
   SUB_CODE VARCHAR2(10),
   SUB_NAME VARCHAR2(30) NOT NULL,
   SUB_EXP VARCHAR2(2000) NOT NULL,
   SUB_TIME NUMBER(10) NOT NULL,
   CONSTRAINT D_SUBJECT_PK PRIMARY KEY(SUB_CODE)
);

CREATE TABLE D_STUCOU(
   SCSEQ VARCHAR2(10),
   COU_CODE VARCHAR2(10) NOT NULL,
   STU_ID VARCHAR2(12) NOT NULL,
   CONSTRAINT D_STUCOU_PK PRIMARY KEY(SCSEQ)
);

CREATE TABLE D_COURSE(
   COU_CODE VARCHAR2(10),
   TEA_ID VARCHAR2(12) NOT NULL,
   COU_NAME VARCHAR2(100) NOT NULL,
   COU_EXP VARCHAR2(2000) NOT NULL,
   STARTDATE DATE NOT NULL,
   TOTALTIME NUMBER(10),
   STATE CHAR(1) NOT NULL,
   ENDDATE DATE,
   COU_CNT NUMBER(10) NOT NULL,
   CONSTRAINT D_COURSE_PK PRIMARY KEY(COU_CODE)
);

CREATE TABLE D_STUDENT(
   STU_ID VARCHAR2(12),
   STU_NAME VARCHAR2(10) NOT NULL,
   STU_PW VARCHAR2(100) NOT NULL,
   STU_PHONE VARCHAR2(40) NOT NULL,
   STU_DELFLAG CHAR(1) NOT NULL,
   CONSTRAINT D_STUDENT_PK PRIMARY KEY(STU_ID)
);

CREATE TABLE D_TEACHER(
   TEA_ID VARCHAR2(12),
   TEA_NAME VARCHAR2(10) NOT NULL,
   TEA_PW VARCHAR2(100) NOT NULL,
   TEA_PHONE VARCHAR2(40) NOT NULL,
   FILENAME VARCHAR2(40),
   TEA_DELFLAG CHAR(1) NOT NULL,
   CONSTRAINT D_TEACHER_PK PRIMARY KEY(TEA_ID)
);

CREATE TABLE D_ADMIN(
   ADM_ID VARCHAR2(12),
   ADM_AUTH CHAR(1) NOT NULL,
   ADM_DELFLAG CHAR(1) NOT NULL,
   ADM_PW VARCHAR2(100) NOT NULL,
   CONSTRAINT D_ADMIN_PK PRIMARY KEY(ADM_ID)
);